# Generated by Django 5.1.1 on 2024-09-17 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_departement_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
