# Generated by Django 5.1.1 on 2024-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_subject_subjectmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(default='121'),
            preserve_default=False,
        ),
    ]
